// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonApi: typeof import('./src/components/doc/button/ButtonApi.md')['default']
    ButtonDisabled: typeof import('./src/components/doc/button/ButtonDisabled.vue')['default']
    ButtonProps: typeof import('./src/components/doc/button/ButtonProps.md')['default']
    CardApi: typeof import('./src/components/doc/card/CardApi.md')['default']
    CardHoverable: typeof import('./src/components/doc/card/CardHoverable.vue')['default']
    CardSlot: typeof import('./src/components/doc/card/CardSlot.vue')['default']
    CodeBox: typeof import('./src/components/CodeBox.vue')['default']
    DocButton: typeof import('./src/components/doc/button/DocButton.vue')['default']
    DocCard: typeof import('./src/components/doc/card/DocCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeadNav: typeof import('./src/components/HeadNav.vue')['default']
    IuButton: typeof import('iu-ui')['IuButton']
    IuCard: typeof import('iu-ui')['IuCard']
    IuName: typeof import('./src/components/IuName.vue')['default']
    IuSpace: typeof import('iu-ui')['IuSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}
