// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonApi: typeof import('./src/components/doc/button/ButtonApi.md')['default']
    ButtonDisabled: typeof import('./src/components/doc/button/ButtonDisabled.vue')['default']
    ButtonRound: typeof import('./src/components/doc/button/ButtonRound.vue')['default']
    CardApi: typeof import('./src/components/doc/card/CardApi.md')['default']
    CardBordered: typeof import('./src/components/doc/card/CardBordered.vue')['default']
    CardHoverable: typeof import('./src/components/doc/card/CardHoverable.vue')['default']
    CardSlot: typeof import('./src/components/doc/card/CardSlot.vue')['default']
    CodeBox: typeof import('./src/components/CodeBox.vue')['default']
    DocButton: typeof import('./src/components/doc/button/DocButton.vue')['default']
    DocCard: typeof import('./src/components/doc/card/DocCard.vue')['default']
    DocSpace: typeof import('./src/components/doc/space/DocSpace.vue')['default']
    DocTooltip: typeof import('./src/components/doc/tooltip/DocTooltip.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeadNav: typeof import('./src/components/HeadNav.vue')['default']
    IuButton: typeof import('iu-ui')['IuButton']
    IuCard: typeof import('iu-ui')['IuCard']
    IuCollapseTransition: typeof import('iu-ui')['IuCollapseTransition']
    IuName: typeof import('./src/components/IuName.vue')['default']
    IuSpace: typeof import('iu-ui')['IuSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SpaceApi: typeof import('./src/components/doc/space/SpaceApi.md')['default']
    SpaceAround: typeof import('./src/components/doc/space/SpaceAround.vue')['default']
    SpaceCenter: typeof import('./src/components/doc/space/SpaceCenter.vue')['default']
    SpaceEnd: typeof import('./src/components/doc/space/SpaceEnd.vue')['default']
    SpaceVertical: typeof import('./src/components/doc/space/SpaceVertical.vue')['default']
    SpaceVerticalCenter: typeof import('./src/components/doc/space/SpaceVerticalCenter.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}
