name: Deploy

on:
  push:
    branches:
      - pre

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install

      - name: Build
        run: pnpm site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env: 
          EXTERNAL_REPOSITORY: iu-night/iu-night.github.io
          PUBLISH_BRANCH: main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
